---

- name: Configure grub
  become: yes
  template:
    src: grub.j2
    dest: /etc/default/grub1
    owner: root
    group: root
    mode: '0600'
  register: grub_config

- name: Harden /boot/grub2/grub1.cfg
  become: yes
  file:
    path: /boot/grub2/grub.cfg
    owner: root
    group: root
    mode: '0600'

- name: Run grub2-mkconfig
  become: yes
  command: grub2-mkconfig -o /boot/grub2/grub.cfg
  when: grub_config.changed
